### PR TITLE
chore: workspace true

### LINKED ISSUE #36: Question: Plans to use workspace dependencies?

### PR DESCRIPTION
**Pull request by helio-frota**
Closes #36

### CODE REVIEW

**Review by ctron — CHANGES_REQUESTED** [review]
I am ok with this PR in general.

So far there was grouping of dependencies, and I know it might not have been that explicit. Normal, internal, optionals. (and not necessarily in that order).

I'd like to keep such group also after this change. I don't have a strong opinion on the order, as long as groups themselves are sorted alphabetically (as they already are in this PR).

**Comment by helio-frota** [comment]
Ok I'll take a look thanks :+1:

**Review by ctron — APPROVED** [review]
Thanks!

**Comment by helio-frota** [comment]
I'll change the remaining 

```console
➜  csaf-walker git:(workspace-true) cargo clippy
warning: the following explicit lifetimes could be elided: 'c
  --> sbom/src/discover.rs:47:6
   |
47 | impl<'c> Deref for DiscoveredContext<'c> {
   |      ^^                              ^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
   = note: `#[warn(clippy::needless_lifetimes)]` on by default
help: elide the lifetimes
   |
47 - impl<'c> Deref for DiscoveredContext<'c> {
47 + impl Deref for DiscoveredContext<'_> {
   |

warning: the following explicit lifetimes could be elided: 'a
  --> sbom/src/report/mod.rs:27:6
   |
27 | impl<'a> ReportSink for (&'a str, Arc<Mutex<BTreeMap<String, Vec<String>>>>) {
   |      ^^                   ^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
help: elide the lifetimes
   |
27 - impl<'a> ReportSink for (&'a str, Arc<Mutex<BTreeMap<String, Vec<String>>>>) {
27 + impl ReportSink for (&str, Arc<Mutex<BTreeMap<String, Vec<String>>>>) {
   |

warning: the following explicit lifetimes could be elided: 'r
   --> csaf/src/report/render.rs:297:6
    |
297 | impl<'r> Display for HtmlReport<'r> {
    |      ^^                         ^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
    = note: `#[warn(clippy::needless_lifetimes)]` on by default
help: elide the lifetimes
    |
297 - impl<'r> Display for HtmlReport<'r> {
297 + impl Display for HtmlReport<'_> {
    |

warning: `sbom-walker` (lib) generated 2 warnings (run `cargo clippy --fix --lib -p sbom-walker` to apply 2 suggestions)
warning: `csaf-walker` (lib) generated 1 warning (run `cargo clippy --fix --lib -p csaf-walker` to apply 1 suggestion)
warning: the following explicit lifetimes could be elided: 'r
   --> sbom/sbom-cli/src/cmd/report/render.rs:140:6
    |
140 | impl<'r> Display for HtmlReport<'r> {
    |      ^^                         ^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
    = note: `#[warn(clippy::needless_lifetimes)]` on by default
help: elide the lifetimes
    |
140 - impl<'r> Display for HtmlReport<'r> {
140 + impl Display for HtmlReport<'_> {
    |

warning: `sbom-cli` (bin "sbom") generated 1 warning (run `cargo clippy --fix --bin "sbom"` to apply 1 suggestion)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.17s
➜  csaf-walker git:(workspace-true) rustc -V
rustc 1.83.0 (90b35a623 2024-11-26)
```

**Comment by helio-frota** [comment]
updated, let's see what happens :+1:

**Pull request merged**
